// Code generated by "stringer -type=TokenTag -linecomment"; DO NOT EDIT.

package lang

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[Identifier-1]
	_ = x[Str-2]
	_ = x[Num-3]
	_ = x[Colon-4]
	_ = x[LCurly-5]
	_ = x[RCurly-6]
	_ = x[LParen-7]
	_ = x[RParen-8]
	_ = x[LSquare-9]
	_ = x[RSquare-10]
	_ = x[Equal-11]
	_ = x[EqualEqual-12]
	_ = x[Greater-13]
	_ = x[GreaterEqual-14]
	_ = x[Less-15]
	_ = x[Plus-16]
	_ = x[Star-17]
	_ = x[Comma-18]
	_ = x[Minus-19]
	_ = x[Slash-20]
	_ = x[Var-21]
	_ = x[For-22]
	_ = x[In-23]
	_ = x[If-24]
	_ = x[Return-25]
	_ = x[Continue-26]
	_ = x[Match-27]
	_ = x[Else-28]
	_ = x[Break-29]
	_ = x[Fn-30]
}

const _TokenTag_name = "EOFIdentifierStrNum:{}()[]===>>=<+*,-/varforinifreturncontinuematchelsebreakfn"

var _TokenTag_index = [...]uint8{0, 3, 13, 16, 19, 20, 21, 22, 23, 24, 25, 26, 27, 29, 30, 32, 33, 34, 35, 36, 37, 38, 41, 44, 46, 48, 54, 62, 67, 71, 76, 78}

func (i TokenTag) String() string {
	if i >= TokenTag(len(_TokenTag_index)-1) {
		return "TokenTag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenTag_name[_TokenTag_index[i]:_TokenTag_index[i+1]]
}
